/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Internal;

import Controller.AccountController;
import Controller.CardController;
import Controller.DisplayManager;
import Controller.ExpenseController;
import Model.Entity.Account;
import Model.Enums.CardFlag;
import Model.Enums.CardType;
import Model.Home.Card;
import Model.Home.Expense;
import static View.LoginScreen.email1;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Renan
 */
public class CardViewScreen extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardScreen
     *
     * @throws java.lang.Exception
     */
    CardController cc = new CardController();
    AccountController ac = new AccountController();
    DisplayManager d = new DisplayManager();

    public CardViewScreen() throws SQLException {
        initComponents();
        cc.getFlagList(cmbFlag);
        cc.getTypeList(cmbType);
        setValuesCard();
    }

    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * @throws java.sql.SQLException
     */
    public void setValuesCard() throws SQLException {
        Account account = ac.getAccountByEmail(email1);
        Card card = cc.getCardByAccountId(account.getId());

        txtAnnualValue.setText(card.getAnnualValue().toString());
        txtLimit.setText(card.getLimit().toString());
        txtNumber.setText(card.getNumber().toString());
        chosserClosingDate.setDate(card.getClosingDate());
        cmbFlag.setSelectedItem(card.getFlag());
        cmbType.setSelectedItem(card.getType());
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDespesas2 = new javax.swing.JLabel();
        txtDespesas1 = new javax.swing.JLabel();
        txtLimit = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtDespesas4 = new javax.swing.JLabel();
        txtDespesas = new javax.swing.JLabel();
        cmbFlag = new javax.swing.JComboBox<>();
        cmbType = new javax.swing.JComboBox<>();
        txtDespesas5 = new javax.swing.JLabel();
        txtAnnualValue = new javax.swing.JTextField();
        chosserClosingDate = new com.toedter.calendar.JDateChooser();
        txtDespesas3 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setBackground(new java.awt.Color(30, 30, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, -1, -1));

        txtDespesas2.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas2.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas2.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas2.setText("Número");
        jPanel1.add(txtDespesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 183, 30));

        txtDespesas1.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas1.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas1.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas1.setText("Limite");
        jPanel1.add(txtDespesas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 183, 30));
        jPanel1.add(txtLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 220, 28));
        jPanel1.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 220, 28));

        txtDespesas4.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas4.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas4.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas4.setText("Tipo");
        jPanel1.add(txtDespesas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 183, 30));

        txtDespesas.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas.setText("Bandeira");
        jPanel1.add(txtDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 183, 30));

        jPanel1.add(cmbFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 227, 30));

        jPanel1.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 220, 30));

        txtDespesas5.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas5.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas5.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas5.setText("Valor Atual (Fatura)");
        jPanel1.add(txtDespesas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));
        jPanel1.add(txtAnnualValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 230, 30));

        chosserClosingDate.setDateFormatString("dd-MM-yyyy ");
        jPanel1.add(chosserClosingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 229, 30));

        txtDespesas3.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas3.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas3.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas3.setText("Data de Fechamento");
        jPanel1.add(txtDespesas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 240, 30));

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 100, 40));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Atualizar");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1157, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        try {
            Account account = ac.getAccountByEmail(email1);
            Card card = cc.getCardByAccountId(account.getId());
            ExpenseController exp = new ExpenseController();
            Integer count = 0;
            int delete = JOptionPane.showConfirmDialog(this, "Você irá apagar o cartão, quer continuar?", "Excluir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (delete == JOptionPane.YES_OPTION) {
                List<Expense> es = exp.getExpenseListByAccountId(account.getId());
                if (es != null) {
                    for (Expense e : es) {
                        if (e.getCardId() == card.getId()) {
                            count++;
                        }
                    }
                    if (count > 0) {
                        JOptionPane.showMessageDialog(null, "Você não pode excluir o cartão!"
                                + "\nEle está cadastrado em " + count + " Despesa(s)!");
                    } else {
                        boolean sucesso = cc.deleteCard(card.getId());
                        if (sucesso) {
                            JOptionPane.showMessageDialog(null, "Cartão excluido com sucesso!");
                        } else {
                            JOptionPane.showMessageDialog(null, "Não foi possível excluir o Cartão!");
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExpenseFullScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        try {
            Account account = ac.getAccountByEmail(email1);
            Card card = cc.getCardByAccountId(account.getId());

            Integer number = Integer.parseInt(txtNumber.getText());
            CardType type = (CardType) cmbType.getSelectedItem();
            CardFlag flag = (CardFlag) cmbFlag.getSelectedItem();
            Double limit = Double.parseDouble(txtLimit.getText());
            Double annualValue = 0.00; //Double.parseDouble(txtAnnualValue.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date data = chosserClosingDate.getDate();
            String dataFormatada = sdf.format(data);

            boolean sucesso = cc.updateCard(card.getId(), account.getId(), number, type.getNum(), flag.getNum(), limit, annualValue, dataFormatada);

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Cartão atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Informe os campos corretamente!");
            }

        } catch (SQLException ex) {
            Logger.getLogger(CardsScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser chosserClosingDate;
    private javax.swing.JComboBox<CardFlag> cmbFlag;
    private javax.swing.JComboBox<CardType> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAnnualValue;
    private javax.swing.JLabel txtDespesas;
    private javax.swing.JLabel txtDespesas1;
    private javax.swing.JLabel txtDespesas2;
    private javax.swing.JLabel txtDespesas3;
    private javax.swing.JLabel txtDespesas4;
    private javax.swing.JLabel txtDespesas5;
    private javax.swing.JTextField txtLimit;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
