/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Internal;

import Controller.AccountController;
import Controller.CardController;
import Controller.DisplayManager;
import Model.Entity.*;
import Model.Enums.*;
import View.HomeScreen;
import static View.LoginScreen.email1;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Renan
 */
public class CardsScreen extends javax.swing.JInternalFrame {

    CardController cc = new CardController();
    AccountController ac = new AccountController();
    DisplayManager d = new DisplayManager();

    public CardsScreen() {
        initComponents();
        cc.getFlagList(cmbFlag);
        cc.getTypeList(cmbType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        btnSaveCard = new javax.swing.JButton();
        cmbFlag = new javax.swing.JComboBox<>();
        cmbType = new javax.swing.JComboBox<>();
        txtNumber = new javax.swing.JTextField();
        txtLimit = new javax.swing.JTextField();
        chosserClosingDate = new com.toedter.calendar.JDateChooser();
        txtDespesas = new javax.swing.JLabel();
        txtDespesas1 = new javax.swing.JLabel();
        txtDespesas2 = new javax.swing.JLabel();
        txtDespesas3 = new javax.swing.JLabel();
        txtDespesas4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        pnlFundo.setBackground(new java.awt.Color(30, 30, 60));
        pnlFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSaveCard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveCard.setText("Salvar");
        btnSaveCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveCardMouseClicked(evt);
            }
        });
        pnlFundo.add(btnSaveCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 433, 89, 40));

        pnlFundo.add(cmbFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 227, 30));

        pnlFundo.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 252, 220, 30));
        pnlFundo.add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 158, 220, 28));
        pnlFundo.add(txtLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 350, 220, 28));

        chosserClosingDate.setDateFormatString("dd-MM-yyyy ");
        pnlFundo.add(chosserClosingDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 229, 30));

        txtDespesas.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas.setText("Bandeira");
        pnlFundo.add(txtDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 183, 30));

        txtDespesas1.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas1.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas1.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas1.setText("Limite");
        pnlFundo.add(txtDespesas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 300, 183, 30));

        txtDespesas2.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas2.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas2.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas2.setText("Número");
        pnlFundo.add(txtDespesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 117, 183, 30));

        txtDespesas3.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas3.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas3.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas3.setText("Data de Fechamento");
        pnlFundo.add(txtDespesas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 240, 30));

        txtDespesas4.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas4.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas4.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas4.setText("Tipo");
        pnlFundo.add(txtDespesas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 204, 183, 30));

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });
        pnlFundo.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1018, 11, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveCardMouseClicked

        try {
            Account accountId = ac.getAccountByEmail(email1);
            
            Integer number = Integer.parseInt(txtNumber.getText());
            CardType type = (CardType) cmbType.getSelectedItem();
            CardFlag flag = (CardFlag) cmbFlag.getSelectedItem();
            Double limit = Double.parseDouble(txtLimit.getText());
            Double annualValue = 0.00; //Double.parseDouble(txtAnnualValue.getText());

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date data = chosserClosingDate.getDate();    
            String dataFormatada = sdf.format(data);
                                     
            boolean sucesso = cc.createCard(accountId.getId(), number, type.getNum(), flag.getNum(), limit, annualValue, dataFormatada);
            
            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Cartão salvo com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Informe os campos corretamente!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CardsScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveCardMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        txtNumber.setText(null);
        txtLimit.setText(null);
        chosserClosingDate.setDate(new Date());
        //txtAnnualValue.setText(null);    
    }//GEN-LAST:event_btnLimparMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSaveCard;
    private com.toedter.calendar.JDateChooser chosserClosingDate;
    private javax.swing.JComboBox<CardFlag> cmbFlag;
    private javax.swing.JComboBox<CardType> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JLabel txtDespesas;
    private javax.swing.JLabel txtDespesas1;
    private javax.swing.JLabel txtDespesas2;
    private javax.swing.JLabel txtDespesas3;
    private javax.swing.JLabel txtDespesas4;
    private javax.swing.JTextField txtLimit;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
