/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Internal;

import Model.Enums.*;
import Controller.*;
import Model.Entity.Account;
import Model.Home.*;
import static View.HomeScreen.desktop;
import static View.LoginScreen.email1;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Renan
 */
public class ExpenseViewScreen extends javax.swing.JInternalFrame {

    ExpenseController exp = new ExpenseController();
    AccountController ac = new AccountController();
    CardController c = new CardController();
    CategoryController cat = new CategoryController();
    DisplayManager d = new DisplayManager();

    String email = email1;
    Account account = ac.getAccountByEmail(email);

    public ExpenseViewScreen() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTExpense.getModel();
        jTExpense.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void readTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) jTExpense.getModel();
        List<Expense> expenses = exp.getExpenseListByAccountId(account.getId());
        
        if (expenses != null) {
            for (Expense e : expenses) {
                modelo.addRow(new Object[]{
                    e.getId(),
                    e.getAccountId(),
                    e.getCardId(),
                    e.getCategoryId(),
                    e.getValue(),
                    e.getDate(),
                    e.getDescription(),
                    e.getNumberOfInstallments(),
                    e.getFormOfPayment(),
                    e.getStatus()
                });
            }
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTExpense = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        IconCategoria4 = new javax.swing.JLabel();
        IconCategoria1 = new javax.swing.JLabel();
        IconCategoria2 = new javax.swing.JLabel();
        IconCategoria3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(30, 30, 60));
        setBorder(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jTExpense.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Conta", "Cartao", "Categoria", "Valor", "Data", "Descrição", "Num.Parcelas ", "forma de Pag.", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTExpense);

        IconCategoria4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconCategoria4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD/icons8_search_32px_1.png"))); // NOI18N
        IconCategoria4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        IconCategoria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconCategoria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD/icons8_edit_32px.png"))); // NOI18N
        IconCategoria1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        IconCategoria2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconCategoria2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD/icons8_add_32px.png"))); // NOI18N
        IconCategoria2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconCategoria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconCategoria2MouseClicked(evt);
            }
        });

        IconCategoria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconCategoria3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD/icons8_waste_32px.png"))); // NOI18N
        IconCategoria3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IconCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(IconCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(IconCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(IconCategoria4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconCategoria4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconCategoria2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IconCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IconCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void IconCategoria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCategoria2MouseClicked
        try {
            d.openInternalFrame(desktop, new ExpenseScreen());
        } catch (SQLException ex) {
            Logger.getLogger(ExpenseViewScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IconCategoria2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconCategoria1;
    private javax.swing.JLabel IconCategoria2;
    private javax.swing.JLabel IconCategoria3;
    private javax.swing.JLabel IconCategoria4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTExpense;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
