/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Internal;

import Controller.AccountController;
import Controller.CardController;
import Controller.DisplayManager;
import DAO.AccountDAO;
import Model.Entity.*;
import Model.Enums.*;
import View.HomeScreen;
import static View.HomeScreen.labelAvatar;
import View.LoginScreen;
import static View.LoginScreen.avatar;
import static View.LoginScreen.email1;
import View.RegisterScreen;
import static View.RegisterScreen.ResizeImage;
import static View.RegisterScreen.imgPath;
import static View.RegisterScreen.labelLocalFile;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.sql.Blob;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Renan
 */
public class UserScreen extends javax.swing.JInternalFrame {

    AccountController ac = new AccountController();
    DisplayManager d = new DisplayManager();
    String Email = email1;
    URL l= this.getClass().getResource("Images/user.png");
    public static String imgPath = null;
    public static byte[] imagem= null;

    public UserScreen() throws Exception {
        initComponents();
        blobToImage(avatar,labelAvatar1);
        setInfo();
        btnSelect.setVisible(false);
        txtName.setEditable(false);
        txtEmail.setEditable(false);
        btnSave.setVisible(false);
        
    }
    public static void blobToImage(Blob blobBD, JLabel label) throws Exception {
        //Converte blob em Image
        byte[] image = blobBD.getBytes(1, (int) blobBD.length());
        Image img = Toolkit.getDefaultToolkit().createImage(image);

        //Escala imagen dentro do JLabel (no meu caso o JLabel possui: 272 por 192)
        Image newimg = img.getScaledInstance(111, 111, java.awt.Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(newimg);

        //Apresenta a imagem no componente JLabel
        label.setIcon(imageIcon);
    }
    
    public final void setInfo() throws SQLException{
          String email = HomeScreen.txtEmail.getText();
            Account accountId = ac.getAccountByEmail(email);
            
          
            txtName.setText(ac.getAccountByEmail(email).getFullName());
            txtEmail.setText(ac.getAccountByEmail(email).getEmail());
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            Date data = ac.getAccountByEmail(email).getCeationDate();
            String dataFormatada = sdf.format(data);
            txtDate.setText(dataFormatada);
           
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtDespesas1 = new javax.swing.JLabel();
        txtDespesas2 = new javax.swing.JLabel();
        txtDespesas4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelAvatar1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();

        setBorder(null);

        pnlFundo.setBackground(new java.awt.Color(30, 30, 60));

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setText("EDITAR");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        txtDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDate.setEnabled(false);

        txtDespesas1.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas1.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas1.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas1.setText("Email:");

        txtDespesas2.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas2.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas2.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas2.setText("Nome:");

        txtDespesas4.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas4.setFont(new java.awt.Font("Ruda", 0, 24)); // NOI18N
        txtDespesas4.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDespesas4.setText("Data de Criação:");

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setText("EXCLUIR CONTA");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_32px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        labelAvatar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        labelAvatar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelAvatar1.setMinimumSize(new java.awt.Dimension(30, 20));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("SALVAR");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSelect.setBackground(new java.awt.Color(85, 65, 118));
        btnSelect.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(213, 220, 224));
        btnSelect.setText("Selecionar");
        btnSelect.setBorder(null);
        btnSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectMouseClicked(evt);
            }
        });
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDespesas1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDespesas2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addComponent(labelAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDespesas4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(339, 339, Short.MAX_VALUE))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(labelAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDespesas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDespesas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDate)
                    .addComponent(txtDespesas4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked

            txtName.setEditable(true);
            txtEmail.setEditable(true);
            btnLimpar.setVisible(false);
            btnSave.setVisible(true);
            btnSelect.setVisible(true);
            labelAvatar1.setIcon(null);
            
           
            
            
        
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        
    }//GEN-LAST:event_btnLimparMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectMouseClicked
        selectFile1();
    }//GEN-LAST:event_btnSelectMouseClicked

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed

    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
          if(imgPath != null){
        File img = new File(imgPath);
        byte[] imagem = new byte[(int)img.length()];
        DataInputStream is = null;
        try {
           is = new DataInputStream(          
                   new FileInputStream(imgPath));
       } catch (FileNotFoundException ex) {
            Logger.getLogger(RegisterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            is.readFully(imagem);
       } catch (IOException ex) {
            Logger.getLogger(RegisterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
      try {
           is.close();
       } catch (IOException ex) {
           Logger.getLogger(RegisterScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
        AccountDAO ac1 = new AccountDAO();
        String fullName = txtName.getText();
        String email = txtEmail.getText();
        Integer id = null;
        Object byteImg = imagem;
        
       try {
            id = ac.getAccountByEmail(Email).getId();
        } catch (SQLException ex) {
            Logger.getLogger(UserScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
//     
          boolean sucesso;

        try {
            AccountController ac = new AccountController();
            sucesso = ac.editAccount(fullName, email,byteImg, id);

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "O PROGRAMA SERA REINICIADO PARA QUE AS ALTERAÇOES SEJAM EFETIVADAS.");
                d.openFrame(new HomeScreen());
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Informe os campos corretamente!");
            }
        } catch (HeadlessException | SQLException e) {
        }     catch (Exception ex) {
                  Logger.getLogger(UserScreen.class.getName()).log(Level.SEVERE, null, ex);
              }
        

          }else
                JOptionPane.showMessageDialog(null, "Informe os campos corretamente!");
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel labelAvatar1;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JLabel txtDespesas1;
    private javax.swing.JLabel txtDespesas2;
    private javax.swing.JLabel txtDespesas4;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

     public static void selectFile1() {
         JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Selecionar avatar");
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Imagens (*png, jpg, jpeg)", "png", "jpg", "jpeg")); //SELECIONA O FILTRO DE ARQUIVOS
        fc.setAcceptAllFileFilterUsed(false);  //Limita os filtros de arquivos
        int res = fc.showOpenDialog(null);
       
        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            
            //Limpa a imagem atual do JLabel
            labelAvatar1.setIcon(null);
            imgPath = arquivo.getAbsolutePath();

            //Seta a imagem selecionada
            Image img = new ImageIcon(arquivo.getAbsolutePath()).getImage();

            //Redimensiona a imagen
            Image newimg = img.getScaledInstance(280, 192, java.awt.Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(newimg);

            //Seta a imagem ao componente JLabel
              labelAvatar1.setIcon(ResizeImage(imgPath,null));
        }else{
            imgPath = null;
        }
         
     }
     
     public static ImageIcon ResizeImage(String ImagePath, byte [] pic) {
       ImageIcon Img = null;
       
       if(ImagePath != null){
           Img = new ImageIcon(ImagePath);
       } else{
           Img = new ImageIcon("/Images/user.png");
       }
       Image img = Img.getImage();
       Image newImg = img.getScaledInstance(labelAvatar1.getWidth(), labelAvatar1.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon image = new ImageIcon(newImg);
       return image;
    }
     
}

