/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DisplayManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jocelio
 */
public class HomeScreen extends javax.swing.JFrame {

    DisplayManager d = new DisplayManager();    
    
    public HomeScreen() {
        initComponents();
        setIcon();
        pegarResolucao();
        setLocationRelativeTo(null);  //Carrega o form no centro da tela
    }

    private void pegarResolucao() {         //Calcula a resoluçao para se adaptara diferentes telas
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
        this.setSize((dimensao.width + 5), (dimensao.height - 38));
    }

    private void setIcon() {
        URL url = this.getClass().getResource("/Images/icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        PainelLateral = new javax.swing.JPanel();
        PainelLateralTop = new javax.swing.JPanel();
        txtUser = new javax.swing.JLabel();
        btnReceitas = new javax.swing.JPanel();
        txtReceitas = new javax.swing.JLabel();
        btnDespesas = new javax.swing.JPanel();
        txtDespesas = new javax.swing.JLabel();
        btnCartoes = new javax.swing.JPanel();
        txtCartoes = new javax.swing.JLabel();
        btnCategorias = new javax.swing.JPanel();
        txtCategorias = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        PainelTopo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SaveMoney");
        setResizable(false);

        Background.setBackground(new java.awt.Color(34, 36, 81));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelLateral.setBackground(new java.awt.Color(51, 51, 76));
        PainelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelLateralTop.setBackground(new java.awt.Color(29, 31, 62));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 45, 20);
        flowLayout1.setAlignOnBaseline(true);
        PainelLateralTop.setLayout(flowLayout1);

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Ruda", 0, 36)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("USER");
        PainelLateralTop.add(txtUser);

        PainelLateral.add(PainelLateralTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 80));

        btnReceitas.setBackground(new java.awt.Color(51, 51, 76));
        btnReceitas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReceitasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReceitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReceitasMouseExited(evt);
            }
        });

        txtReceitas.setBackground(new java.awt.Color(255, 255, 255));
        txtReceitas.setFont(new java.awt.Font("Ruda", 0, 36)); // NOI18N
        txtReceitas.setForeground(new java.awt.Color(255, 255, 255));
        txtReceitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReceitas.setText("Receitas");

        javax.swing.GroupLayout btnReceitasLayout = new javax.swing.GroupLayout(btnReceitas);
        btnReceitas.setLayout(btnReceitasLayout);
        btnReceitasLayout.setHorizontalGroup(
            btnReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(btnReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        btnReceitasLayout.setVerticalGroup(
            btnReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(btnReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReceitasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReceitas)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        PainelLateral.add(btnReceitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 310, -1));

        btnDespesas.setBackground(new java.awt.Color(51, 51, 76));
        btnDespesas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDespesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDespesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDespesasMouseExited(evt);
            }
        });

        txtDespesas.setBackground(new java.awt.Color(255, 255, 255));
        txtDespesas.setFont(new java.awt.Font("Ruda", 0, 36)); // NOI18N
        txtDespesas.setForeground(new java.awt.Color(255, 255, 255));
        txtDespesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDespesas.setText("Despesas");

        javax.swing.GroupLayout btnDespesasLayout = new javax.swing.GroupLayout(btnDespesas);
        btnDespesas.setLayout(btnDespesasLayout);
        btnDespesasLayout.setHorizontalGroup(
            btnDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(btnDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        btnDespesasLayout.setVerticalGroup(
            btnDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(btnDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDespesasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDespesas)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        PainelLateral.add(btnDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 310, -1));

        btnCartoes.setBackground(new java.awt.Color(51, 51, 76));
        btnCartoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCartoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCartoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCartoesMouseExited(evt);
            }
        });

        txtCartoes.setBackground(new java.awt.Color(255, 255, 255));
        txtCartoes.setFont(new java.awt.Font("Ruda", 0, 36)); // NOI18N
        txtCartoes.setForeground(new java.awt.Color(255, 255, 255));
        txtCartoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCartoes.setText("Cartões");

        javax.swing.GroupLayout btnCartoesLayout = new javax.swing.GroupLayout(btnCartoes);
        btnCartoes.setLayout(btnCartoesLayout);
        btnCartoesLayout.setHorizontalGroup(
            btnCartoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(btnCartoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtCartoes, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        btnCartoesLayout.setVerticalGroup(
            btnCartoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(btnCartoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCartoesLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCartoes)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        PainelLateral.add(btnCartoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 249, 310, -1));

        btnCategorias.setBackground(new java.awt.Color(51, 51, 76));
        btnCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseExited(evt);
            }
        });

        txtCategorias.setBackground(new java.awt.Color(255, 255, 255));
        txtCategorias.setFont(new java.awt.Font("Ruda", 0, 36)); // NOI18N
        txtCategorias.setForeground(new java.awt.Color(255, 255, 255));
        txtCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCategorias.setText("Categorias");

        javax.swing.GroupLayout btnCategoriasLayout = new javax.swing.GroupLayout(btnCategorias);
        btnCategorias.setLayout(btnCategoriasLayout);
        btnCategoriasLayout.setHorizontalGroup(
            btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        btnCategoriasLayout.setVerticalGroup(
            btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCategoriasLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCategorias)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        PainelLateral.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 323, 310, -1));

        Background.add(PainelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 720));

        desktop.setMaximumSize(new java.awt.Dimension(1170, 640));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        Background.add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 1170, 640));

        PainelTopo.setBackground(new java.awt.Color(34, 36, 81));
        PainelTopo.setPreferredSize(new java.awt.Dimension(1043, 115));

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setFont(new java.awt.Font("Ruda", 0, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("PRINCIPAL");

        javax.swing.GroupLayout PainelTopoLayout = new javax.swing.GroupLayout(PainelTopo);
        PainelTopo.setLayout(PainelTopoLayout);
        PainelTopoLayout.setHorizontalGroup(
            PainelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTopoLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PainelTopoLayout.setVerticalGroup(
            PainelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTopoLayout.createSequentialGroup()
                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.add(PainelTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1171, 86));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    //EFEITO HOVER//
    public void mouseEnteredButton(JPanel p, JLabel l){
        p.setBackground(new Color(29, 31, 62));  
        //l.setFont(font);
    }

    public void mouseExitedButton(JPanel p, JLabel l){
        p.setBackground(new Color(51, 51, 76));
    }
    //FIM DO EFEITO//    
    
    private void btnReceitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceitasMouseEntered
        mouseEnteredButton(btnReceitas, txtReceitas);
    }//GEN-LAST:event_btnReceitasMouseEntered

    private void btnReceitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceitasMouseExited
        mouseExitedButton(btnReceitas, txtReceitas);
    }//GEN-LAST:event_btnReceitasMouseExited

    private void btnDespesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDespesasMouseEntered
        mouseEnteredButton(btnDespesas, txtDespesas);
    }//GEN-LAST:event_btnDespesasMouseEntered

    private void btnDespesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDespesasMouseExited
        mouseExitedButton(btnDespesas, txtDespesas);
    }//GEN-LAST:event_btnDespesasMouseExited

    private void btnCartoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartoesMouseEntered
        mouseEnteredButton(btnCartoes, txtCartoes);
    }//GEN-LAST:event_btnCartoesMouseEntered

    private void btnCartoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartoesMouseExited
        mouseExitedButton(btnCartoes, txtCartoes);
    }//GEN-LAST:event_btnCartoesMouseExited

    private void btnCategoriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseEntered
        mouseEnteredButton(btnCategorias, txtCategorias);
    }//GEN-LAST:event_btnCategoriasMouseEntered

    private void btnCategoriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseExited
        mouseExitedButton(btnCategorias, txtCategorias);
    }//GEN-LAST:event_btnCategoriasMouseExited

    private void btnReceitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceitasMouseClicked
        txtTitulo.setText("RECEITAS");        
    }//GEN-LAST:event_btnReceitasMouseClicked

    private void btnDespesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDespesasMouseClicked
        txtTitulo.setText("DESPESAS");
    }//GEN-LAST:event_btnDespesasMouseClicked

    private void btnCartoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartoesMouseClicked
        txtTitulo.setText("CARTÕES");
        
        d.OpenCard(desktop);
    }//GEN-LAST:event_btnCartoesMouseClicked

    private void btnCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseClicked
        txtTitulo.setText("CATEGORIAS");
        
        d.OpenCategory(desktop);
    }//GEN-LAST:event_btnCategoriasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel PainelLateral;
    private javax.swing.JPanel PainelLateralTop;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JPanel btnCartoes;
    private javax.swing.JPanel btnCategorias;
    private javax.swing.JPanel btnDespesas;
    private javax.swing.JPanel btnReceitas;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel txtCartoes;
    private javax.swing.JLabel txtCategorias;
    private javax.swing.JLabel txtDespesas;
    private javax.swing.JLabel txtReceitas;
    private javax.swing.JLabel txtTitulo;
    public static javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
